#!/bin/bash

key_path="./confs/ssh-chat-key"

err() {
    if [ $? -ne 0 ]; then
    exit 1
    fi
}

build() {
    #create an empty file if dosen't exist
    touch ./confs/admins
    if [[ ! -f "$key_path" ]]; then
        echo "Gennerating SSH key..."
        ssh-keygen -t rsa -b 4096 -N '' -f $key_path
    fi

    docker-compose build; err

    docker-compose up -d; err
}

connect() {
    if [ -z "$user_name" ]; then
    read -p "Enter your name [$USER]: " user_name
    user_name=${name:-$USER}
    fi

    clear
    ssh $user_name@localhost -p 2022
}


build
connect